routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('siswa', 'SiswaController');

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    // menghubungkan tabel siswa
    protected $table = 'siswa';

    // menyimpan data tanpa timestamps(created_at, updated_at, delete_at)
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Siswa;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Tampil data
        $data = Siswa::all();
        return view('siswa.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = new Siswa();
        $data->nama = $request->nama;
		$data->alamat = $request->alamat;
		$data->email = $request->email;
        $data->save();
        return redirect()->route('siswa.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Detail siswa
        $data = Siswa::find($id);
        return view('siswa.lihat', ['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Form Edit siswa
        $data = Siswa::where('id', $id)->get();
        return view('siswa.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Simpan Edit siswa
        $data = Siswa::where('id', $id)->first();
        $data->nama = $request->nama;
        $data->alamat = $request->alamat;
        $data->email = $request->email;
        $data->save();
        return redirect()->route('siswa.index')->with('alert-success', 'Data berhasil dirubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // delete
        $data = Siswa::where('id', $id)->first();
        $data->delete();
        return redirect()->route('siswa.index');
    }
}

resources/views/siswa/create.blade.php
<form action="{{ route('siswa.store') }}" method="post">
    {{ csrf_field() }}
    <label>Nama :</label>
    <input type="text" name="nama"/>
    <label>Alamat :</label>
    <input type="text" name="alamat"/>
    <label>Email :</label>
    <input type="text" name="email"/>
    <button type="submit">Submit</button>
    <button type="reset">Cancel</button>
</form>

resources/views/siswa/edit.blade.php
@foreach($data as $datas)
<form action="{{ route('siswa.update', $datas->id) }}" method="post">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
    <label>Nama:</label>
    <input type="text" name="nama" value="{{ $datas->nama }}"/>    
    <label>Alamat:</label>
    <input type="text" name="alamat" value="{{ $datas->alamat }}"/>
    <label>Email:</label>
    <input type="text" name="email" value="{{ $datas->email }}"/>
    <button type="submit">Submit</button>
    <button type="reset">Cancel</button>
</form>
@endforeach

resources/views/siswa/index.blade.php
<a href="{{ route('siswa.create') }}">Tambah Siswa</a>
<table>
    <thead>
        <th>No.</th>
        <th>Nama</th>
        <th>Email</th>
        <th>Alamat</th>
        <th>Option</th>
    </thead>
    <tbody>
        @php
            $no = 1;
        @endphp
        @foreach ($data as $items)
            <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $items->nama }}</td>
                <td>{{ $items->email }}</td>
                <td>{{ $items->alamat }}</td>
                <td>
                    <form action="{{ route('siswa.destroy', $items->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a href="{{ route('siswa.show', $items->id) }}">Lihat</a>
                        <a href="{{ route('siswa.edit', $items->id) }}">Edit</a>
                        <button type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/siswa/lihat.blade.php
<a href="{{ route('siswa.index') }}">Lihat Data Siswa</a>
<h1>Data Siswa {{ $data->nama }}</h1>
<table>
    <tbody>
        <tr>
            <td>Nama</td>
            <td>:</td>
            <td>{{ $data->nama }}</td>
        </tr>
        <tr>
            <td>Alamat</td>
            <td>:</td>
            <td>{{ $data->alamat }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>:</td>
            <td>{{ $data->email }}</td>
        </tr>
    </tbody>
</table>